name: CI Test Workflow

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f1000391@ds.study.iitm.ac.in
        run: echo "Hello, world!"
